### ISSUE TITLE
Rewrite branch direction

### ISSUE THREAD

**Issue by hellbe** [O365/python-o365#101]
Hey @janscas ,

The rewrite branch looks very promising, great work! What's the current status/plan for it? Wouldn't it make sense to break out to a new project and library given the fact that the interface has changed completely?

All the best

**Comment by janscas** [comment]
I'm following the project on my repository for the moment. Mine is some commits ahead.

https://github.com/janscas/py-o365

But the original plan was to work on only one project together with @Narcolapser.
Hope we can integrate the project and have only one for the community in the near future.

Just to let you know: my project has grown on complexity because I have to maintain compatibility between Office365 api version 1 and 2 and Microsoft Graph. On november 1st 2018 Office365 api version 1 will be deprecated and therefore the project will receive a major overhaul.

**Comment by hellbe** [comment]
@janscas makes perfect sense to have one project to collaborate on. I was just thinking that it makes sense to make it a new repo/project/name since the changes will be breaking from the existing library.

Make sense to drop Office 365 API v1 given the short timeframe to deprecation, to reduce complexity somewhat. 

I could probably contribute a bit of time to such a project, currently relying on Basic Auth so I need to migrate to a better setup anyway.

**Comment by roycem90** [comment]
This is now merged and released as O365 v1.0
