### ISSUE TITLE
ssl connection leak

### ISSUE THREAD

**Issue by rasjani** [O365/python-o365#151]
I know i might be doing something wrong but when i use get_session and have provided a token, i'll get some dangling ssl connections.  For the existing reference, i can still get the session from connection and call close() on it but if there has been multiple get_session() calls it almost feels like the ssl session initialized from https://github.com/O365/python-o365/blob/master/O365/connection.py#L462 (line 363 in 1.0.0 release) should be closing the existing one or atleast keep track of it and close the underlying requests.session .. 

Ps. sorry for bad bug report, hope this makes atleast some sense :(

**Comment by janscas** [comment]
I don't get why you need to call `get_session` manually... 
Anyway you will notice that in this library, where I need to get the session, I first check for the existence of a current session like this:

```
if not self.session:
    self.get_session()
```
This prevents multiple calls to get_session to occur.
This is done on purpose because some internal may want to have a new fresh session (this don't occurs for the moment).

**Comment by rasjani** [comment]
As i said, sorry for bad report.  

But.. there is zero code  or documentation to imply that oath2 session must be closed by the user. Even if the session is initialized only once, it has to be explicitly closed or requests will notify user about it.

**Comment by janscas** [comment]
Well, when the script dies the session dies and so any hanging connection. If you want to close any connection ... why don't you call account.con.session.close().

I don't see why we should close the session and even more difficult will be to decide "when".

**Comment by rasjani** [comment]
1. Yes, its not really a leak because things will be "cleaned up" at exit - but people will get worried when they see warnings like that and it might affect them when reviewing the project in detrimental way. 
2. Yes, i'm already calling close() in my __del__  - so its not really a problem for *me*, just saying that maybe some house keeping might be in order.

But the statement "I don't see why we should" is not really true from my perspective. Essentially, what happens is that  O365 code creates instance of  `OAuth2Session` and storing that into self.session in `Connection` class. This is "internal" implementation of connection class and essentially, connection class should do its own housekeeping.  This is even more troublesome since essentially, the session object isnt even implemented in o365 but its from requests session and actual api is two levels down in inheritance chain.

About when to destroy it  -  Maybe in __del__ of connection class. When overriding self.session if its already initialized ? Or maybe self.session should only be active during token creation & refresh and closed after either of the task is done. And then recreated/closed if its needed later on. 

Im not that familiar yet with the patterns/architecture of O365 so coming up with pull request at this point isn't really a fast option.  But at least, documentation change to tell the user that they need to explicitly close either account.session or connection.session .. 

PS. Im not saying i wont help on this if so required, just that i dont have much time at the moment and what ever i could whip up in fast pace definitely wont be the optimal solution...

**Comment by janscas** [comment]
I think you don't completely understand how the api works. We can't destroy the session because it's used on every api call to the microsoft servers (generating the token, refreshing the token, and also requesting any resources).
So as long as the user is using the library, the session is needed.
I can not arbitrarily decide when it should be a good moment to close the session.

Also note that there is no guarantee that the destructor method will be called on interpreter exit (Cpython).

But, that said, I aggree that we should add some cleanup. I'll commit a fix to close the session on the `__del__` method of the `Connection` class.

However I don't think anyone (but the garbage collector) will call the `__del__` method on the connection manually.
