### ISSUE TITLE
o365 oauth error

### ISSUE THREAD

**Issue by boxdox** [O365/python-o365#156]
```
from O365 import oauth_authentication_flow

result = oauth_authentication_flow('client_id', 'client_secret', ['scopes_required'])
```

whenever i run the url i get, it just says that "This doesn't look like a work or school email. You can't sign in here with a personal account. Use your work or school account instead."

Any Idea?

**Comment by davres1** [comment]
how do you get url?

**Comment by boxdox** [comment]
> Can you paste the scopes that you are passing to `oauth_authentication_flow`?
> 
> There are some scopes that are not allowed for personal accounts. For example: `Mail.Read.Shared` is not allowed.

'https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send'



> how do you get url?

if you run the above piece of code, it automatically gives you the url (afaik)

**Comment by davres1** [comment]
yes but request token is hanging.

result_url = input('https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=c2e9f47a-b15c-4ea8-b36c-58e8391377e3&redirect_uri=https%3A%2F%2Foutlook.office365.com%2Fowa%2F&scope=https%3A%2F%2Fgraph.microsoft.com%2FMail.ReadWrite+https%3A%2F%2Fgraph.microsoft.com%2FMail.Send&state=Eqe4WbXzdtdH8WDZOAV5Z4wThjfvvF&access_type=offline')

**Comment by roycem90** [comment]
@davres1 check out this, it  https://o365.github.io/python-o365/latest/html/usage/account.html#authenticating-your-account

Use the account to get into the library.

**Comment by nickyspag** [comment]
Like @boxdox I was also having trouble completing this authentication process successfully - I kept getting redirected to a login screen AFTER granting the auth with error that I need to log in with a school or work email,  even with scope that is listed as available for personal accounts.

``
account = Account((settings.O365_ID, settings.O365_SECRET), scopes=['https://graph.microsoft.com/Calendars.ReadWrite'])
url = account.connection.get_authorization_url()
print(url)
# visit URL in browser
``

The first time ( or each time I added a new scope, or after revoking permissions) then I got sent to  the permission screen to grant the permission, correctly. But after saying YES I would then get redirected to another login screen like this:

![image](https://user-images.githubusercontent.com/144062/50448540-94b9ed00-092a-11e9-8283-f7e43bca23b3.png)

And then trying to log in again I would get:

![image](https://user-images.githubusercontent.com/144062/50448557-aac7ad80-092a-11e9-962b-6fe493cdb2bd.png)

What I was able to do however was to open javascript console and in network tab with logs persisted I could catch the URL of the redirect. I suspect microsoft have since added some redirect on that page since these O365 docs were written?

Anyway this is a way to specify your own redirect URL (just make sure it matches what you set as the Redirect URI under Platform for your app in https://apps.dev.microsoft.com/)

``
url = account.connection.get_authorization_url(redirect_uri='https://example.com/O365auth')
print(url)
response_url = input('Paste return URL: ')
account.connection.request_token(response_url)
``

**Comment by davres1** [comment]
I spend lot of time to figure it out but here are the final steps.

from O365 import Account
account = Account(credentials=('client-id','secert'),scopes=['message_all'])

account.authenticate(scopes=['message_all'])

this will give url which you will open in bower and pass back the url .

**Comment by janscas** [comment]
You only need to authenticate once.

The best way is by using account.authenticate.

This will take a param called scopes that must contain a list of [scope helpers](https://o365.github.io/python-o365/latest/html/usage/account.html#setting-scopes).

So just do this to authenticate (assuming you want to use Microsoft Graph):

```python
credentials = (client_id, client_secret)
account = Account(credentials, protocol=WHATEVERPROTOCOL)
account.authenticate(['scope_helper1', 'scope_helper2'])
```
If this succeed you will now have a o365_token.txt stored with the credentials. 
So you can now just use the account class without calling authenticate again.
You don't have to pass scopes to the Account constructor because those are stored in the token file.


Now, If the scope helpers are useless for you, then you can't use account.authenticate.
You must use:

```python
credentials = (client_id, client_secret)
con = Connection(credentials, scopes=['https://graph.microsoft.com/Calendars.ReadWrite', '...'])
consent_url = con.get_authorization_url()

# here visit consent_url, log in and accept the consent screen.
# Then copy the result url and pass it to con.request_token:
result = con.request_token(result_url)

if result is True:
    print('Success! You have the token file stored')
```

**Comment by janscas** [comment]
Can we close this?

**Comment by davres1** [comment]
Yes pls

Thanks
Sumit Davre

On Jan 9, 2019, at 5:58 AM, Alejandro Casanovas <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Can we close this?
