### ISSUE TITLE
No easy way to query for recurring events in calendar

### ISSUE THREAD

**Issue by sharst** [O365/python-o365#161]
I'm writing a small application to query my calendars for events in the next 10 minutes. This works great for single events with a query that asks start < (in 10 minutes) < end of event. 
However, since recurring events have the start and end of only the first occurrence in the object, they are missed.
Am I mistaken or is there currently no easy way to get them? The only way to go seems to be to look at all recurring events manually one by one and check if one of the recurrences falls in the period of interest.

**Comment by janscas** [comment]
Hi, 
the graph docs state that the current way of asking for events only returns singleInstance events and seriesMaster (the first event in a recurring series) but not all the occurrences.

> Retrieve a list of events in a calendar. The list contains single instance meetings and series masters.

We choose to follow the same pattern.

I have just added a new method to the Event class that allows to query for all the recurring events of a seriesMaster event. This is already released with pypi version 1.0.3.

The next step is to implement CalendarViews that will allow to easily query all kind of events.
I'll add this to the project board.

@roycem90 this should be added to the docs `Event.get_occurrences`

Thanks

**Comment by janscas** [comment]
I have just find some time to implement this.

Now you can call Calendar.get_events (or Schedule.get_events) with the param `include_recurring=True` (True is the default btw).
The only caveat is that with `include_recurring=True` you MUST fix a start datetime and an end datetime using the Query object.

@Narcolapser @roycem90  This is a breaking change because previously this method did not return any recurring events, but it is important enough to be changed. If you disagree let me know to rollback this.

I've just released 1.0.4 to Pypi with this changes.

**Comment by sharst** [comment]
Awesome, thanks a lot for your help! I can confirm it works.

**Comment by tokr94** [comment]
When calling `Calendar.get_events` with `include_recurring=True` and a query where end should be greater equal some value and start should be less equal some second value (that is still greater than the first), I receive an `HTTPError: StartDateTime should be earlier or equal to EndDateTime`.

```
start = datetime.datetime.now()
end = start + datetime.timedelta(hours=1)
query = cal.new_query('end').greater_equal(start)
query.chain('and').on_attribute('start').less_equal(end)
```

What I want to do is fetching all events touching the given time range. Everything works fine when I exclude recurring events. Seems like startTime and endTime get changed accidently otherwise.

Thanks in advance.

**Comment by janscas** [comment]
Hi,
when using `include_recurring=True` you are getting all the recurring events. Under the hood, this calls microsoft graph for what is called a "CalendarView". When doing so, microsoft does not allow to include filters on start and end dates
You can only say (for example) "give me all the events from this datetime to this other datetime". This only checks for the "start date" of each event.

There is nothing we can do to get microsoft graph servers to further filter this list.

You can however, filter the returned events by code by iterating them.

So when using `include_recurring=True` the query does not take into account the modifiers `greater_equal` or `less_equal. It only expects to receive a 'start datetime' and an 'end datetime'.

I know it's not intuitive right now, but it's also not intuitive how microsoft graph resolves this.

If you have any ideas on how to make this more "transparent" to the end user let me know.

**Comment by tokr94** [comment]
Hi Janscas,

great, thanks for the rapid response. Maybe you should at least mention this under [readme#calendar](https://github.com/O365/python-o365/#calendar). In the given example you use the default value `include_recurring=True` but also filter on dates and change the modifiers. That's what made me think this is possible. So either don't change modifiers or explicitely exclude recurring events.

In General: if you just want to wrap the exact behavior of Microsoft Graph API this is fine but I would this method expect to already filter on the desired date range, e.g. my case.

Thanks

**Comment by janscas** [comment]
I'll modify the readme.
Thanks

**Comment by tokr94** [comment]
So, basically, Graph API does not allow to filter on (recurring) events that end in the desired range? Wow.

**Comment by janscas** [comment]
Yep
