### ISSUE TITLE
Forward message as attachment

### ISSUE THREAD

**Issue by frennkie** [O365/python-o365#202]
I want to forward a message as an attachment. As far as I see the API has two separate forward endpoints.

[**forward:**](https://docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0)

> Forward a message. The message is saved in the Sent Items folder.

[**createforward:**](https://docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0)

> Create a draft to forward the specified message. You can then update the draft to add content to the body or change other message properties, or, simply send the draft.

As far as I see it neither of these directly support this. Or am I missing something? **So I guess I have to manually create a new message and attach the content of original message, right?**

Btw: `python-o365` currently only implements `createForward`. Is it planned to add `forward`?

**Comment by janscas** [comment]
Hi, yes, the Graph Api exposes this two methods. However, the first one: '/forward' is very limited. It only allows to include a single unformatted comment and a list of 'to' recipients. You can't do anything more. 

Because of this limitations, we believe it's better to use the createforward approach.

So, if you want to forward a message with O365, you have to call `message.forward` to get a message that you can manipulate and is a "saved"/"unsend" forward message. Then you can manipulate the message and call `message.send`. to effectively send the forwarded message.

**Comment by frennkie** [comment]
Hi, I managed to implement my use case.

I use the Beta API to download the complete raw message and then create a new message and add the original message as Base64 encoded attachment. Is there a way to do this without saving a temporary file to disc and passing this the Attachment? 

Anyway, I think this issue is can be closed.

**Comment by janscas** [comment]
> Is there a way to do this without saving a temporary file to disc and passing this the Attachment?

You can use 'io' to handle in-memory files.

```python
import io

in_memory_file = io.StringIO("my string of data")  # or io.BytesIO if you are handling bytes.
```

**Comment by stefanadelbert** [comment]
This is something I'd like to be able to do, i.e. send an email with attachments which come from memory as opposed to files on disk. It's not clear to me how to attach data I have in `io.ByteIO` (e,g, PNG data) or `io.StringIO` (e.g. CSV data) to an email. Could I ask you please to give an example?
