### ISSUE TITLE
Sorry I get the message "Error: (insecure_transport) OAuth 2 MUST utilize https"

### ISSUE THREAD

**Issue by EpicHigh** [O365/python-o365#286]
My script is as same as the example.

```python
account = Account(credentials)
account.authenticate(scopes=['basic', 'message_all'])
```

I go to the link in the console, and then I copy the URL after it's redirected.

```console
Visit the following url to give consent:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&XXX
Paste the authenticated url here:
"https://login.microsoftonline.com/common/oauth2/nativeclient?code=XXXX"
```

I get the error message

```console
Something go wrong. Please try again.
Unable to fetch auth token. Error: (insecure_transport) OAuth 2 MUST utilize https.
```

**Comment by janscas** [comment]
I can't reproduce your error.

**Comment by grahamoptibrium** [comment]
I got the same error in ipython; I fixed it by changing the redirect/reply url of my application in the Azure console to be an HTTPS one.

**Comment by neilkatin** [comment]
I ran into this error today; I'm adding to this ticket to document for others what the problem and fix was for me.

(This was running in a cygwin64 environment on windows)

I got the OAuth 2 MUST utilize https error repeatably.

The root cause: my terminal was in a strange state, and pre-pending "<ESC> [ 200 ~" to the pasted string.  This made the URL look like it didn't start with ```https://`` (the string that oauthlib was comparing to the submitted URL).  This was confirmed by running ```od -c``` and pasting in any copied text.

Just that one window had the problem; others did not.

Running ```reset``` to reinitialize the terminal fixed the problem.
