### ISSUE TITLE
Prefer: outlook.body-content-type="text"

### ISSUE THREAD

**Issue by rena2damas** [O365/python-o365#289]
I see the application once supported editing headers and this was addressed [before](https://github.com/O365/python-o365/issues/102). The application seems to have been redesigned since then and you can now pass it as argument to ```get``` in ```Connection```.

However, for my case, I am trying to get a new message with ```inbox_folder.get_message(object_id=xxx)```. This ```get_message``` takes no ```kwargs``` so that it could pass to the ```self.con.get(url)``` method inside. That way I could set the headers.

Shouldn't ```get_message``` take ```kwargs``` so that I have better control over properties like headers in order to grant more flexibility to the methods used?

**Comment by janscas** [comment]
Why do you need Prefer: outlook.body-content-type="text"?

When getting messages using the default html you can also extract the text by calling:

```python
message.get_body_text()
```

**Comment by rena2damas** [comment]
Yea that's true. ```BeautifulSoap``` does the trick.

**Comment by johanovic** [comment]
Actually that's not entirely true, BeautifulSoup extracts the text from the html. If the text part of the multipart email message is different from the html part, then the current method fails to see that difference.

**Comment by johanovic** [comment]
Also bs4 doesn't always work flawlessly. The encoding/decoding by graph is quite good.

**Comment by janscas** [comment]
@johanovic any proposals?

**Comment by johanovic** [comment]
I think it should be possible to set custom headers in all api calls of the library. That would a lot of extra tooling available with relatively little effort. Because the graph docs regularly focus on using specific headers, I would think it makes sense to include options to do so in python-O365.

In terms of development, there are at least two options: 1) a built-in headers kwargs to functions such as get_messages, 2) an abstraction layer that enables people to write custom Message classes with different headers.

Relevant: https://docs.microsoft.com/en-us/graph/outlook-create-send-messages#reading-messages-with-control-over-the-body-format-returned

**Comment by janscas** [comment]
I think it's not posible to set custom headers. I've read that a long time ago so maybe it has change.

**Comment by 3rock618** [comment]
I was able to accomplish this with: 
`account.con.session.headers.update({'Prefer': 'outlook.body-content-type="text"'})`

**Comment by rena2damas** [comment]
@3rock618 thanks for the tip, gotta give it a try.
