### ISSUE TITLE
[Question] Are we able to pull total number of emails in specific folder?

### ISSUE THREAD

**Issue by lia-cha-avalara** [O365/python-o365#335]
When i run something like...

inbox = mailbox.inbox_folder()
total_emails = inbox.total_items_count

this returns the default value of 0. If i try to dig in deeper by using the get_messages() method, that returns a paginator obj which I can't just call len() on. I feel like writing a message property into a list and calling len() on that would just add more work. Am I just missing something simple?

**Comment by janscas** [comment]
When using the "special" mailbox folder constructors we don't retrieve the folder from the server. Instead we just create the object. This is on purpose because you usually don't need this folder properties.

So, when using 'mailbox.inbox_folder()` or `maibox.junk_folder()`, etc... you will have to call `refresh_folder`.

so.

```python
inbox = mailbox.inbox_folder()
inbox.refresh_folder()
total_emails = inbox.total_items_count  # should return the total messages in the folder.
```

You can also use the method `get_folder` which will return the folder with all it's properties like:

```python
from O365.utils import OutlookWellKnowFolderNames

inbox = mailbox.get_folder(folder_id=OutlookWellKnowFolderNames.INBOX.value)
total_emails = inbox.total_items_count
```
