### ISSUE TITLE
get messages from other folders

### ISSUE THREAD

**Issue by hiroki14da** [O365/python-o365#69]
Hi, I uses Inbox class to get emails. But I don't know how to get messages from other folders such as SentItems, Drafts and DeletedItems. Is it possible?

**Comment by roycem90** [comment]
available in the new inbox now, please check the readme for FluentInbox

**Comment by Narcolapser** [comment]
@hiroki14da can you give the FluentInbox a try and see if it fulfills your needs? Thanks.

**Comment by Adniel** [comment]
I can fetch messages using FluentInbox from other folders than inbox but fail to understand how to use the `from_folder` filter when trying to access sub folders. I have an `Import` folder in my inbox. Should it be possible?

**Comment by roycem90** [comment]
i haven't tried it yet, but just try with the folder name alone, if it doesn't work then let me know

**Comment by Xalaxis** [comment]
@roycem90 When I try to use from_folder() it only lists the root level directories.

**Comment by jasonlopez01** [comment]
Agree it would be nice to add functionality, maybe to the FluentInbox.from_folder method, to add a parent ID in order to get messages from a subfolder. That method just sets the 'working' folder url, so the work around I'm currently using just does so manually
`inbox_id = inbox.get_folder(value='Inbox', by='DisplayName')['Id']`
`subfolder_id = inbox.get_folder(parent_id=inbox_id, value='subfolder_name', by='DisplayName')['Id']`
`inbox.url = inbox._get_url('folder').format(folder_id=subfolder_id)`
Now you can get and search messages from the subfolder
`inbox.search('Subject:test subject').fetch(count=20)`

**Comment by jasonlopez01** [comment]
Definitely, submitted the pull request. Nice to contribute, this has been a pretty useful library, great having the Outlook 365 auth and api abstracted a bit

**Comment by Narcolapser** [comment]
Thanks for your help. I'll try to get a new version out soon.
